import type { SystemConnection, Vec3 } from "@/crates/building-graph/types";
import { addAssembly, addBox, MAT, PROV_EDU, segmentBox } from "./helper";
import { P, Y, halfL, halfW } from "./params";
import type { Registry } from "./registry";

const CABLE = 0.016;

function cable(
  reg: Registry,
  id: string,
  label: string,
  a: Vec3,
  b: Vec3,
  tags: string[],
  short: string,
  purpose: string,
  extra?: { explodeGroup?: string; explodeVector?: Vec3; local?: Vec3; parentId?: string; stage?: number },
) {
  const { center, size } = segmentBox(a, b, CABLE);
  addBox(reg, {
    id,
    type: "cable",
    label,
    parentId: extra?.parentId ?? "assembly.electrical",
    trade: "electrical",
    center,
    size,
    material: MAT.cable,
    stage: extra?.stage ?? 17,
    explodeGroup: extra?.explodeGroup ?? "assembly.electrical",
    explodeVector: extra?.explodeVector ?? [0, 1.3, 0],
    localExplodeVector: extra?.local ?? [0, 0.35, 0],
    tradeExplodeVector: [0, 2.0, 0],
    tags,
    short,
    purpose,
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: id, role: "conductor" },
    dependencies: ["slab.basement"],
  });
}

export function addElectrical(reg: Registry) {
  addAssembly(reg, {
    id: "assembly.electrical",
    label: "Electrical system",
    trade: "electrical",
    center: [0.8, 1.4, 0.6],
    size: [8, 4.2, 6],
    stage: 17,
    dependencies: ["assembly.wall.front", "slab.basement"],
    explodeVector: [0, 1.6, 0],
    short: "Service, panel, branch circuits and devices of this specimen.",
    purpose: "Teach topology from source to load. Not electromagnetic simulation and not a CEC inspection.",
    tags: ["electrical"],
  });

  const panelX = 1.15;
  const panelZ = halfW - P.fdnT - 0.12;
  const panelY = Y.footingTop + 1.15;
  const slabY = Y.footingTop + 0.18;
  const joistY = Y.sillTop + P.joist.d * 0.45;
  const deviceY = Y.floorTop + 0.32;
  const switchY = Y.floorTop + 1.1;
  const lightY = Y.wallTop - 0.12;

  addBox(reg, {
    id: "electrical.service.entry",
    type: "service-entry",
    label: "Service entry (concept)",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [halfL + 0.08, slabY + 0.7, 1.35],
    size: [0.28, 0.18, 0.18],
    material: MAT.steel,
    stage: 17,
    explodeGroup: "assembly.foundation",
    explodeVector: [1.6, 0.2, 0],
    tradeExplodeVector: [0, 1.8, 0],
    tags: ["electrical", "service"],
    short: "Utility / consumer service boundary, shown as a teaching object.",
    purpose: "Mark where the service arrives. Metering and utility rules are not modelled.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.service.entry", role: "source" },
    dependencies: ["fdn.right"],
  });

  addBox(reg, {
    id: "penetration.foundation.right.electrical.001",
    type: "penetration",
    label: "Electrical service penetration",
    parentId: "assembly.foundation",
    trade: "electrical",
    center: [halfL - P.fdnT / 2, slabY + 0.7, 1.35],
    size: [P.fdnT + 0.04, 0.12, 0.12],
    material: MAT.concrete,
    stage: 17,
    explodeGroup: "assembly.foundation",
    explodeVector: [1.3, 0, 0],
    tags: ["electrical", "penetration"],
    short: "Opening where the service enters the foundation wall.",
    purpose: "Record the host/trade pair so later sealing rules can attach. No CEC text is encoded.",
    penetration: {
      hostId: "fdn.right",
      tradeComponentId: "electrical.service.entry",
      purpose: "service-entry",
    },
    dependencies: ["electrical.service.entry"],
  });

  addBox(reg, {
    id: "electrical.panel.main",
    type: "panel",
    label: "Main panel / loadcentre",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [panelX, panelY, panelZ],
    size: [0.42, 0.72, 0.12],
    material: MAT.panel,
    stage: 17,
    explodeGroup: "assembly.electrical",
    explodeVector: [0, 0.6, 1.4],
    localExplodeVector: [0, 0.2, 0.45],
    tradeExplodeVector: [0, 1.6, 0],
    tags: ["electrical", "panel", "mechanical"],
    short: "The house loadcentre in the mechanical area.",
    purpose: "Source node for branch circuits. Ampacity, interrupting rating and CEC rules are not evaluated.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.panel.main", role: "panel" },
    dependencies: ["slab.basement"],
  });

  addBox(reg, {
    id: "electrical.breaker.main",
    type: "breaker",
    label: "Main disconnect / breaker",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [panelX - 0.12, panelY + 0.22, panelZ - 0.02],
    size: [0.08, 0.16, 0.06],
    material: MAT.device,
    stage: 17,
    explodeGroup: "assembly.electrical",
    explodeVector: [0, 0.7, 1.5],
    tradeExplodeVector: [0, 1.7, 0],
    tags: ["electrical", "breaker"],
    short: "Main overcurrent / disconnect representation.",
    purpose: "Show that branch circuits originate at an overcurrent device. This is topology, not a trip curve.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.breaker.main", role: "overcurrent" },
    dependencies: ["electrical.panel.main"],
  });

  const branches = [
    { id: "electrical.breaker.kitchen", label: "Kitchen branch breaker", y: -0.08 },
    { id: "electrical.breaker.bath", label: "Bathroom branch breaker", y: -0.18 },
    { id: "electrical.breaker.lighting", label: "Lighting branch breaker", y: -0.28 },
    { id: "electrical.breaker.receptacles", label: "Receptacle branch breaker", y: -0.38 },
    { id: "electrical.breaker.mechanical", label: "Mechanical branch breaker", y: -0.48 },
  ];
  for (const b of branches) {
    addBox(reg, {
      id: b.id,
      type: "breaker",
      label: b.label,
      parentId: "assembly.electrical",
      trade: "electrical",
      center: [panelX + 0.1, panelY + b.y, panelZ - 0.02],
      size: [0.07, 0.08, 0.05],
      material: MAT.device,
      stage: 17,
      explodeGroup: "assembly.electrical",
      explodeVector: [0, 0.65, 1.45],
      tradeExplodeVector: [0, 1.65, 0],
      tags: ["electrical", "breaker"],
      short: "A branch overcurrent device in the panel.",
      purpose: "Protect one modelled circuit. Device ratings are demonstration placeholders.",
      visualization: "TOPOLOGY / STATE VISUALIZATION",
      provenance: PROV_EDU,
      system: { systemId: "system.electrical", nodeId: b.id, role: "overcurrent" },
      dependencies: ["electrical.breaker.main"],
    });
  }

  addBox(reg, {
    id: "electrical.bonding.main",
    type: "bonding",
    label: "Equipment bonding conductor (concept)",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [panelX, Y.footingTop + 0.25, panelZ],
    size: [0.02, 0.5, 0.02],
    material: MAT.copper,
    stage: 17,
    explodeGroup: "assembly.electrical",
    explodeVector: [0, 0.4, 1.2],
    tags: ["electrical", "bonding"],
    short: "A bonding path at the panel, shown conceptually.",
    purpose: "Point at grounding/bonding as a real system. Electrode details and CEC bonding rules are not copied.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.bonding.main", role: "bonding" },
    dependencies: ["electrical.panel.main"],
  });

  cable(
    reg,
    "electrical.cable.service.001",
    "Service conductors (concept)",
    [halfL + 0.05, slabY + 0.7, 1.35],
    [panelX + 0.2, panelY + 0.2, panelZ],
    ["electrical", "service"],
    "Run from the service entry to the panel.",
    "Connect source to loadcentre. Conductor size is not evaluated.",
  );

  cable(
    reg,
    "electrical.cable.riser.001",
    "Home-run riser through floor",
    [panelX, panelY + 0.35, panelZ - 0.2],
    [panelX, joistY, 2.4],
    ["electrical"],
    "Cables leaving the panel toward the floor deck.",
    "Move branch circuits into the framed floor.",
  );

  addBox(reg, {
    id: "penetration.floor.electrical.001",
    type: "penetration",
    label: "Electrical floor penetration",
    parentId: "assembly.floor",
    trade: "electrical",
    center: [panelX, Y.floorTop - 0.04, 2.55],
    size: [0.1, 0.1, 0.1],
    material: MAT.wood,
    stage: 17,
    explodeGroup: "assembly.floor",
    explodeVector: [0, 0.8, 0],
    tags: ["electrical", "penetration"],
    short: "Opening where home runs pass the floor deck.",
    purpose: "Host/trade penetration seam for later firestopping and air sealing.",
    penetration: {
      hostId: "subfloor.0",
      tradeComponentId: "electrical.cable.riser.001",
      purpose: "branch-riser",
    },
  });

  // Kitchen circuit along front wall
  cable(
    reg,
    "electrical.cable.kitchen.001",
    "Kitchen branch in joist bay",
    [panelX, joistY, 2.4],
    [2.75, joistY, 2.9],
    ["electrical", "kitchen"],
    "Kitchen circuit routed in the floor cavity.",
    "A cable occupies framed space rather than a schematic line.",
  );
  cable(
    reg,
    "electrical.cable.kitchen.002",
    "Kitchen branch up to devices",
    [2.75, joistY, 2.9],
    [2.75, deviceY, 3.22],
    ["electrical", "kitchen"],
    "Rise into the kitchen service wall.",
    "Arrive at kitchen device boxes.",
    { explodeGroup: "assembly.wall.front", explodeVector: [0, 0.3, 2.0], local: [0, 0.1, 0.35], parentId: "assembly.wall.front" },
  );

  addBox(reg, {
    id: "electrical.box.kitchen.001",
    type: "device-box",
    label: "Kitchen receptacle box",
    parentId: "assembly.wall.front",
    trade: "electrical",
    center: [2.35, deviceY, halfW - 0.16],
    size: [0.1, 0.1, 0.08],
    material: MAT.steel,
    stage: 17,
    explodeGroup: "assembly.wall.front",
    explodeVector: [0, 0.2, 2.1],
    localExplodeVector: [0, 0.05, 0.4],
    tradeExplodeVector: [0, 1.5, 0],
    tags: ["electrical", "kitchen", "window-wall"],
    short: "Device box in the kitchen / front wall.",
    purpose: "A real box in the stud space, not a floating icon.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.box.kitchen.001", role: "box" },
    dependencies: ["electrical.cable.kitchen.002"],
  });
  addBox(reg, {
    id: "electrical.device.receptacle.kitchen.001",
    type: "receptacle",
    label: "Kitchen receptacle",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [2.35, deviceY, halfW - 0.12],
    size: [0.11, 0.11, 0.04],
    material: MAT.device,
    stage: 21,
    explodeGroup: "assembly.wall.front",
    explodeVector: [0, 0.15, 2.3],
    localExplodeVector: [0, 0, 0.55],
    tradeExplodeVector: [0, 1.4, 0],
    tags: ["electrical", "kitchen", "device"],
    short: "A kitchen receptacle on the service wall.",
    purpose: "A load on the kitchen branch. GFCI/AFCI rules are not copied from the CEC.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.device.receptacle.kitchen.001", role: "load" },
    dependencies: ["electrical.box.kitchen.001"],
  });
  addBox(reg, {
    id: "electrical.device.receptacle.kitchen.002",
    type: "receptacle",
    label: "Kitchen counter receptacle",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [3.15, Y.floorTop + 1.05, halfW - 0.12],
    size: [0.11, 0.11, 0.04],
    material: MAT.device,
    stage: 21,
    explodeGroup: "assembly.wall.front",
    explodeVector: [0, 0.2, 2.3],
    localExplodeVector: [0, 0, 0.55],
    tags: ["electrical", "kitchen", "device"],
    short: "Second kitchen receptacle.",
    purpose: "Show more than one load on the kitchen branch.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.device.receptacle.kitchen.002", role: "load" },
    dependencies: ["electrical.box.kitchen.001"],
  });
  addBox(reg, {
    id: "electrical.device.switch.kitchen.001",
    type: "switch",
    label: "Kitchen light switch",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [1.85, switchY, halfW - 0.12],
    size: [0.08, 0.12, 0.04],
    material: MAT.device,
    stage: 21,
    explodeGroup: "assembly.wall.front",
    explodeVector: [0, 0.2, 2.2],
    localExplodeVector: [0, 0, 0.5],
    tags: ["electrical", "kitchen", "device"],
    short: "Switch for the kitchen luminaire.",
    purpose: "A control device on the lighting topology.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.device.switch.kitchen.001", role: "control" },
    dependencies: ["electrical.cable.lighting.001"],
  });
  addBox(reg, {
    id: "electrical.device.luminaire.kitchen.001",
    type: "luminaire",
    label: "Kitchen luminaire",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [2.6, lightY, 2.6],
    size: [0.28, 0.06, 0.28],
    material: MAT.steel,
    stage: 21,
    explodeGroup: "assembly.electrical",
    explodeVector: [0, 1.4, 0],
    tags: ["electrical", "kitchen", "device"],
    short: "Ceiling light over the kitchen.",
    purpose: "A lighting load. Photometrics are not modelled.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.device.luminaire.kitchen.001", role: "load" },
    dependencies: ["electrical.device.switch.kitchen.001"],
  });

  // Bathroom circuit
  cable(
    reg,
    "electrical.cable.bath.001",
    "Bath branch in joist bay",
    [panelX, joistY, 2.4],
    [-2.25, joistY, -1.17],
    ["electrical", "bath"],
    "Bathroom circuit crossing the floor structure.",
    "Route through joist bays to the wet wall.",
  );
  cable(
    reg,
    "electrical.cable.bath.002",
    "Bath branch in wet wall",
    [-2.25, joistY, -1.17],
    [-2.25, switchY, -1.17],
    ["electrical", "bath"],
    "Rise inside the bathroom partition.",
    "Serve bath devices from inside the framed wall.",
    { explodeGroup: "assembly.wall.bath", explodeVector: [1.7, 0.3, 0], local: [0.45, 0.1, 0], parentId: "assembly.wall.bath" },
  );
  cable(
    reg,
    "electrical.cable.bath.003",
    "Bath branch to device box",
    [-2.25, switchY, -1.17],
    [-2.25, switchY, -0.75],
    ["electrical", "bath"],
    "Horizontal run in the wet-wall cavity to the device box.",
    "Stay between studs rather than through them.",
    { explodeGroup: "assembly.wall.bath", explodeVector: [1.7, 0.3, 0], local: [0.45, 0.1, 0], parentId: "assembly.wall.bath" },
  );
  addBox(reg, {
    id: "penetration.wall.bath.electrical.001",
    type: "penetration",
    label: "Bath wall electrical penetration",
    parentId: "assembly.wall.bath",
    trade: "electrical",
    center: [-2.25, Y.floorTop, -1.17],
    size: [0.08, 0.06, 0.08],
    material: MAT.wood,
    stage: 17,
    explodeGroup: "assembly.wall.bath",
    explodeVector: [1.4, 0.1, 0],
    tags: ["electrical", "penetration", "bath"],
    short: "Plate opening for the bathroom cable.",
    purpose: "Host/trade penetration on the wet wall.",
    penetration: {
      hostId: "assembly.wall.bath.plate.bottom",
      tradeComponentId: "electrical.cable.bath.002",
      purpose: "branch-cable",
    },
  });
  addBox(reg, {
    id: "electrical.box.bath.001",
    type: "device-box",
    label: "Bathroom device box",
    parentId: "assembly.wall.bath",
    trade: "electrical",
    center: [-2.32, switchY, -0.75],
    size: [0.08, 0.11, 0.1],
    material: MAT.steel,
    stage: 17,
    explodeGroup: "assembly.wall.bath",
    explodeVector: [1.8, 0.25, 0],
    localExplodeVector: [0.5, 0, 0],
    tags: ["electrical", "bath"],
    short: "Box in the bathroom wet wall.",
    purpose: "Receive the bath switch and nearby devices.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.box.bath.001", role: "box" },
    dependencies: ["electrical.cable.bath.002"],
  });
  addBox(reg, {
    id: "electrical.device.switch.bath.001",
    type: "switch",
    label: "Bathroom switch",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [-2.42, switchY, -0.75],
    size: [0.04, 0.12, 0.08],
    material: MAT.device,
    stage: 21,
    explodeGroup: "assembly.wall.bath",
    explodeVector: [1.9, 0.2, 0],
    localExplodeVector: [0.6, 0, 0],
    tags: ["electrical", "bath", "device"],
    short: "Switch for the bathroom luminaire and a cue for the exhaust.",
    purpose: "A control on the bath branch.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.device.switch.bath.001", role: "control" },
    dependencies: ["electrical.box.bath.001"],
  });
  addBox(reg, {
    id: "electrical.device.receptacle.bath.001",
    type: "receptacle",
    label: "Bathroom receptacle",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [-2.42, deviceY + 0.55, -0.4],
    size: [0.04, 0.11, 0.11],
    material: MAT.device,
    stage: 21,
    explodeGroup: "assembly.wall.bath",
    explodeVector: [1.9, 0.15, 0],
    localExplodeVector: [0.6, 0, 0],
    tags: ["electrical", "bath", "device"],
    short: "Bathroom receptacle beside the lavatory.",
    purpose: "A wet-location device in the teaching wall. Protection-device rules are not copied.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.device.receptacle.bath.001", role: "load" },
    dependencies: ["electrical.box.bath.001"],
  });
  addBox(reg, {
    id: "electrical.device.luminaire.bath.001",
    type: "luminaire",
    label: "Bathroom luminaire",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [-3.2, lightY, -1.1],
    size: [0.22, 0.06, 0.22],
    material: MAT.steel,
    stage: 21,
    explodeGroup: "assembly.electrical",
    explodeVector: [0, 1.3, 0],
    tags: ["electrical", "bath", "device"],
    short: "Bathroom ceiling light.",
    purpose: "Lighting load on the bath branch.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.device.luminaire.bath.001", role: "load" },
    dependencies: ["electrical.device.switch.bath.001"],
  });

  // Lighting + general receptacle on the teaching window wall
  cable(
    reg,
    "electrical.cable.lighting.001",
    "Lighting branch",
    [panelX, joistY, 2.4],
    [0.2, joistY, 2.9],
    ["electrical", "lighting"],
    "Lighting circuit toward the front wall.",
    "Serve switches and luminaires.",
  );
  cable(
    reg,
    "electrical.cable.lighting.002",
    "Front-wall lighting rise",
    [0.2, joistY, 2.9],
    [0.2, switchY, halfW - 0.18],
    ["electrical", "lighting", "window-wall"],
    "Rise beside the teaching window.",
    "A cable in the window-wall cavity.",
    { explodeGroup: "assembly.wall.front", explodeVector: [0, 0.25, 2.0], local: [0, 0.1, 0.4], parentId: "assembly.wall.front" },
  );
  addBox(reg, {
    id: "electrical.box.front.001",
    type: "device-box",
    label: "Front wall switch box",
    parentId: "assembly.wall.front",
    trade: "electrical",
    center: [-1.7, switchY, halfW - 0.16],
    size: [0.1, 0.11, 0.08],
    material: MAT.steel,
    stage: 17,
    explodeGroup: "assembly.wall.front",
    explodeVector: [0, 0.2, 2.15],
    localExplodeVector: [0, 0, 0.45],
    tags: ["electrical", "window-wall"],
    short: "Device box beside the front door.",
    purpose: "A box in the teaching wall assembly.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.box.front.001", role: "box" },
    dependencies: ["electrical.cable.lighting.002"],
  });
  addBox(reg, {
    id: "electrical.device.switch.front.001",
    type: "switch",
    label: "Entry light switch",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [-1.7, switchY, halfW - 0.12],
    size: [0.08, 0.12, 0.04],
    material: MAT.device,
    stage: 21,
    explodeGroup: "assembly.wall.front",
    explodeVector: [0, 0.15, 2.35],
    localExplodeVector: [0, 0, 0.55],
    tags: ["electrical", "device", "window-wall"],
    short: "Switch at the front door.",
    purpose: "Control the entry luminaire.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.device.switch.front.001", role: "control" },
    dependencies: ["electrical.box.front.001"],
  });
  addBox(reg, {
    id: "electrical.device.luminaire.front.001",
    type: "luminaire",
    label: "Entry luminaire",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [-2.55, Y.wallTop - 0.25, halfW - 0.2],
    size: [0.18, 0.14, 0.18],
    material: MAT.steel,
    stage: 21,
    explodeGroup: "assembly.wall.front",
    explodeVector: [0, 0.4, 2.1],
    tags: ["electrical", "device"],
    short: "Light at the front door.",
    purpose: "A lighting load on the lighting branch.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.device.luminaire.front.001", role: "load" },
    dependencies: ["electrical.device.switch.front.001"],
  });
  addBox(reg, {
    id: "electrical.device.receptacle.front.001",
    type: "receptacle",
    label: "Front wall receptacle",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [1.15, deviceY, halfW - 0.12],
    size: [0.11, 0.11, 0.04],
    material: MAT.device,
    stage: 21,
    explodeGroup: "assembly.wall.front",
    explodeVector: [0, 0.1, 2.3],
    localExplodeVector: [0, 0, 0.5],
    tags: ["electrical", "device", "window-wall"],
    short: "General receptacle on the teaching wall.",
    purpose: "A general-purpose load used for TRACE to the panel.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.device.receptacle.front.001", role: "load" },
    dependencies: ["electrical.cable.receptacles.001"],
  });
  cable(
    reg,
    "electrical.cable.receptacles.001",
    "Receptacle branch in joist bay",
    [panelX, joistY, 2.4],
    [1.15, joistY, halfW - 0.38],
    ["electrical"],
    "General receptacle circuit in the floor cavity.",
    "Stay under the subfloor until the teaching wall.",
  );
  cable(
    reg,
    "electrical.cable.receptacles.002",
    "Receptacle rise at front wall",
    [1.15, joistY, halfW - 0.38],
    [1.15, deviceY, halfW - 0.18],
    ["electrical"],
    "Rise in the front-wall cavity to the receptacle.",
    "The only above-floor run is the wall riser, not a diagonal through the room.",
    { explodeGroup: "assembly.wall.front", explodeVector: [0, 0.2, 1.8], local: [0, 0.05, 0.3], parentId: "assembly.wall.front" },
  );

  // Mechanical loads
  cable(
    reg,
    "electrical.cable.mechanical.001",
    "Mechanical branch",
    [panelX - 0.05, panelY - 0.2, panelZ - 0.15],
    [-1.05, slabY + 1.15, 1.05],
    ["electrical", "mechanical"],
    "Circuit to the water heater and indoor mechanical equipment.",
    "Fixed loads in the mechanical area.",
  );
  addBox(reg, {
    id: "electrical.device.waterheater.load",
    type: "device-box",
    label: "Water-heater connection",
    parentId: "assembly.electrical",
    trade: "electrical",
    center: [-1.05, slabY + 1.22, 1.28],
    size: [0.12, 0.1, 0.08],
    material: MAT.steel,
    stage: 17,
    explodeGroup: "assembly.electrical",
    explodeVector: [0, 0.5, 1.0],
    tags: ["electrical", "mechanical"],
    short: "Connection at the electric water heater.",
    purpose: "A fixed mechanical load on its own branch.",
    visualization: "TOPOLOGY / STATE VISUALIZATION",
    provenance: PROV_EDU,
    system: { systemId: "system.electrical", nodeId: "electrical.device.waterheater.load", role: "load" },
    dependencies: ["electrical.cable.mechanical.001"],
  });
}

export const ELECTRICAL_CONNECTIONS: SystemConnection[] = [
  { id: "el.service-panel", from: "electrical.service.entry", to: "electrical.cable.service.001", kind: "circuit" },
  { id: "el.cable-panel", from: "electrical.cable.service.001", to: "electrical.panel.main", kind: "circuit" },
  { id: "el.panel-mainbr", from: "electrical.panel.main", to: "electrical.breaker.main", kind: "circuit" },
  { id: "el.panel-bond", from: "electrical.panel.main", to: "electrical.bonding.main", kind: "bonding" },
  { id: "el.main-kit", from: "electrical.breaker.main", to: "electrical.breaker.kitchen", kind: "circuit" },
  { id: "el.main-bath", from: "electrical.breaker.main", to: "electrical.breaker.bath", kind: "circuit" },
  { id: "el.main-lt", from: "electrical.breaker.main", to: "electrical.breaker.lighting", kind: "circuit" },
  { id: "el.main-rec", from: "electrical.breaker.main", to: "electrical.breaker.receptacles", kind: "circuit" },
  { id: "el.main-mech", from: "electrical.breaker.main", to: "electrical.breaker.mechanical", kind: "circuit" },
  { id: "el.kit-c1", from: "electrical.breaker.kitchen", to: "electrical.cable.kitchen.001", kind: "circuit" },
  { id: "el.kit-c2", from: "electrical.cable.kitchen.001", to: "electrical.cable.kitchen.002", kind: "circuit" },
  { id: "el.kit-box", from: "electrical.cable.kitchen.002", to: "electrical.box.kitchen.001", kind: "circuit" },
  { id: "el.kit-r1", from: "electrical.box.kitchen.001", to: "electrical.device.receptacle.kitchen.001", kind: "circuit" },
  { id: "el.kit-r2", from: "electrical.box.kitchen.001", to: "electrical.device.receptacle.kitchen.002", kind: "circuit" },
  { id: "el.bath-c1", from: "electrical.breaker.bath", to: "electrical.cable.bath.001", kind: "circuit" },
  { id: "el.bath-c2", from: "electrical.cable.bath.001", to: "electrical.cable.bath.002", kind: "circuit" },
  { id: "el.bath-c3", from: "electrical.cable.bath.002", to: "electrical.cable.bath.003", kind: "circuit" },
  { id: "el.bath-box", from: "electrical.cable.bath.003", to: "electrical.box.bath.001", kind: "circuit" },
  { id: "el.bath-sw", from: "electrical.box.bath.001", to: "electrical.device.switch.bath.001", kind: "circuit" },
  { id: "el.bath-rec", from: "electrical.box.bath.001", to: "electrical.device.receptacle.bath.001", kind: "circuit" },
  { id: "el.bath-lt", from: "electrical.device.switch.bath.001", to: "electrical.device.luminaire.bath.001", kind: "circuit" },
  { id: "el.lt-c1", from: "electrical.breaker.lighting", to: "electrical.cable.lighting.001", kind: "circuit" },
  { id: "el.lt-c2", from: "electrical.cable.lighting.001", to: "electrical.cable.lighting.002", kind: "circuit" },
  { id: "el.lt-box", from: "electrical.cable.lighting.002", to: "electrical.box.front.001", kind: "circuit" },
  { id: "el.lt-sw", from: "electrical.box.front.001", to: "electrical.device.switch.front.001", kind: "circuit" },
  { id: "el.lt-lum", from: "electrical.device.switch.front.001", to: "electrical.device.luminaire.front.001", kind: "circuit" },
  { id: "el.lt-kit-sw", from: "electrical.cable.lighting.001", to: "electrical.device.switch.kitchen.001", kind: "circuit" },
  { id: "el.lt-kit-lum", from: "electrical.device.switch.kitchen.001", to: "electrical.device.luminaire.kitchen.001", kind: "circuit" },
  { id: "el.rec-c", from: "electrical.breaker.receptacles", to: "electrical.cable.receptacles.001", kind: "circuit" },
  { id: "el.rec-c2", from: "electrical.cable.receptacles.001", to: "electrical.cable.receptacles.002", kind: "circuit" },
  { id: "el.rec-d", from: "electrical.cable.receptacles.002", to: "electrical.device.receptacle.front.001", kind: "circuit" },
  { id: "el.mech-c", from: "electrical.breaker.mechanical", to: "electrical.cable.mechanical.001", kind: "circuit" },
  { id: "el.mech-wh", from: "electrical.cable.mechanical.001", to: "electrical.device.waterheater.load", kind: "circuit" },
  { id: "el.riser", from: "electrical.breaker.kitchen", to: "electrical.cable.riser.001", kind: "circuit" },
  { id: "el.riser2", from: "electrical.cable.riser.001", to: "electrical.cable.kitchen.001", kind: "circuit" },
];
