import type { SystemConnection, Vec3 } from "@/crates/building-graph/types";
import { addAssembly, addBox, MAT, PROV_EDU, segmentBox } from "./helper";
import { P, Y, halfL, halfW } from "./params";
import type { Registry } from "./registry";

function duct(
  reg: Registry,
  id: string,
  label: string,
  a: Vec3,
  b: Vec3,
  sizeMinor: number,
  tags: string[],
  short: string,
  purpose: string,
  extra?: { explodeGroup?: string; explodeVector?: Vec3; local?: Vec3; parentId?: string; role?: string },
) {
  const { center, size } = segmentBox(a, b, sizeMinor);
  addBox(reg, {
    id,
    type: "duct",
    label,
    parentId: extra?.parentId ?? "assembly.hvac",
    trade: "hvac",
    center,
    size,
    material: MAT.steel,
    stage: 16,
    explodeGroup: extra?.explodeGroup ?? "assembly.hvac",
    explodeVector: extra?.explodeVector ?? [0, 1.2, 0],
    localExplodeVector: extra?.local ?? [0, 0.3, 0],
    tradeExplodeVector: [0, 1.9, 0],
    tags,
    short,
    purpose,
    visualization: "SCHEMATIC AIRFLOW",
    provenance: PROV_EDU,
    system: { systemId: "system.hvac", nodeId: id, role: extra?.role ?? "duct" },
    dependencies: ["slab.basement"],
  });
}

export function addHvac(reg: Registry) {
  addAssembly(reg, {
    id: "assembly.hvac",
    label: "HVAC / ventilation",
    trade: "hvac",
    center: [0.4, 1.1, 0],
    size: [8, 4, 7],
    stage: 16,
    dependencies: ["slab.basement", "assembly.wall.back"],
    explodeVector: [0, 1.5, 0],
    short: "All-electric heat pump, ducts, HRV and exhaust of this specimen.",
    purpose: "Show equipment relationships. Not a load calculation, refrigerant design or commissioning.",
    tags: ["hvac"],
  });

  const slabY = Y.footingTop + 0.12;
  const indoor: Vec3 = [0.35, slabY + 0.55, 1.55];
  const outdoor: Vec3 = [1.35, P.grade + 0.42, -halfW - 0.85];
  // 2×10 joists are 235 mm. Trunks this size hang below the joists in the basement.
  const underDuctY = Y.sillTop - 0.14;
  const plenum: Vec3 = [indoor[0], underDuctY, indoor[2]];

  addBox(reg, {
    id: "hvac.heatpump.outdoor.001",
    type: "heat-pump-outdoor",
    label: "Air-source heat-pump outdoor unit",
    parentId: "assembly.hvac",
    trade: "hvac",
    center: outdoor,
    size: [0.9, 0.75, 0.38],
    material: MAT.steel,
    stage: 16,
    explodeGroup: "assembly.hvac",
    explodeVector: [0, 0.4, -1.6],
    tradeExplodeVector: [0, 1.5, 0],
    tags: ["hvac", "mechanical"],
    short: "Outdoor unit of the all-electric heat pump.",
    purpose: "The outdoor half of the heating/cooling plant. Capacity is not sized.",
    visualization: "SCHEMATIC AIRFLOW",
    provenance: PROV_EDU,
    system: { systemId: "system.hvac", nodeId: "hvac.heatpump.outdoor.001", role: "plant" },
    dependencies: ["slab.basement"],
  });

  addBox(reg, {
    id: "hvac.heatpump.indoor.001",
    type: "heat-pump-indoor",
    label: "Indoor air handler",
    parentId: "assembly.hvac",
    trade: "hvac",
    center: indoor,
    size: [0.7, 0.95, 0.55],
    material: MAT.steel,
    stage: 16,
    explodeGroup: "assembly.hvac",
    explodeVector: [0, 0.7, 1.1],
    tradeExplodeVector: [0, 1.4, 0],
    tags: ["hvac", "mechanical"],
    short: "Indoor unit / air handler in the mechanical area.",
    purpose: "Condition and move air. This is a relationship model, not a coil design.",
    visualization: "SCHEMATIC AIRFLOW",
    provenance: PROV_EDU,
    system: { systemId: "system.hvac", nodeId: "hvac.heatpump.indoor.001", role: "plant" },
    dependencies: ["slab.basement"],
  });

  const yRef = indoor[1] + 0.2;
  const xRef = outdoor[0];
  const zInside = -halfW + P.fdnT + 0.04;
  const zThrough = -halfW + P.fdnT / 2;
  const zOutside = outdoor[2];
  const refDia = 0.03;
  const refA: Vec3 = [indoor[0] + 0.2, yRef, indoor[2] - 0.3];
  const refB: Vec3 = [xRef, yRef, indoor[2] - 0.3];
  const refC: Vec3 = [xRef, yRef, zInside];
  const refD: Vec3 = [xRef, yRef, zOutside];
  function refLine(id: string, label: string, a: Vec3, b: Vec3, extra?: { penetrationHost?: string }) {
    const { center, size } = segmentBox(a, b, refDia);
    addBox(reg, {
      id,
      type: "refrigerant-line",
      label,
      parentId: "assembly.hvac",
      trade: "hvac",
      center,
      size,
      material: MAT.copper,
      stage: 16,
      explodeGroup: "assembly.hvac",
      explodeVector: [0, 0.5, -0.6],
      tags: ["hvac"],
      short: "A simplified refrigerant-line concept between indoor and outdoor units.",
      purpose: "Show that the two units are one machine. Charge, diameter and brazing are not taught as engineering.",
      visualization: "SCHEMATIC AIRFLOW",
      provenance: PROV_EDU,
      system: { systemId: "system.hvac", nodeId: id, role: "refrigerant" },
      run: { from: a, to: b, flow: "from-to" },
      dependencies: ["hvac.heatpump.indoor.001"],
    });
    void extra;
  }
  refLine("hvac.refrigerant.001", "Refrigerant line (indoor run)", refA, refB);
  refLine("hvac.refrigerant.002", "Refrigerant line (to wall)", refB, refC);
  refLine("hvac.refrigerant.003", "Refrigerant line (through wall)", [xRef, yRef, zInside], [xRef, yRef, -halfW - 0.05]);
  refLine("hvac.refrigerant.004", "Refrigerant line (outdoor)", [xRef, yRef, -halfW - 0.05], refD);

  addBox(reg, {
    id: "penetration.wall.back.hvac.001",
    type: "penetration",
    label: "Refrigerant line penetration",
    parentId: "assembly.wall.back",
    trade: "hvac",
    center: [xRef, yRef, zThrough],
    size: [0.12, 0.12, P.fdnT + 0.04],
    material: MAT.concrete,
    stage: 16,
    explodeGroup: "assembly.foundation",
    explodeVector: [0, 0.2, -1.3],
    tags: ["hvac", "penetration"],
    short: "Opening where the line set leaves the enclosure.",
    purpose: "Host/trade penetration for later sealing.",
    penetration: {
      hostId: "fdn.back",
      tradeComponentId: "hvac.refrigerant.003",
      purpose: "refrigerant-line",
    },
  });

  addBox(reg, {
    id: "hvac.condensate.001",
    type: "condensate",
    label: "Condensate drain (concept)",
    parentId: "assembly.hvac",
    trade: "hvac",
    center: [indoor[0] - 0.45, slabY + 0.12, indoor[2]],
    size: [0.55, 0.025, 0.025],
    material: MAT.pvc,
    stage: 16,
    explodeGroup: "assembly.hvac",
    explodeVector: [-0.4, 0.3, 0],
    tags: ["hvac", "mechanical"],
    short: "Condensate path from the indoor unit.",
    purpose: "Show that cooling produces water that must go somewhere. Trap details are not a code quote.",
    visualization: "SCHEMATIC AIRFLOW",
    provenance: PROV_EDU,
    system: { systemId: "system.hvac", nodeId: "hvac.condensate.001", role: "condensate" },
    dependencies: ["hvac.heatpump.indoor.001"],
  });

  addBox(reg, {
    id: "hvac.hrv.001",
    type: "hrv",
    label: "HRV / ventilation unit",
    parentId: "assembly.hvac",
    trade: "hvac",
    center: [1.55, slabY + 0.38, 1.55],
    size: [0.55, 0.45, 0.4],
    material: MAT.steel,
    stage: 16,
    explodeGroup: "assembly.hvac",
    explodeVector: [0.8, 0.5, 1.0],
    tags: ["hvac", "ventilation", "mechanical"],
    short: "Heat-recovery ventilator in the mechanical area.",
    purpose: "Balanced ventilation concept. Airflow rates are not commissioned here.",
    visualization: "SCHEMATIC AIRFLOW",
    provenance: PROV_EDU,
    system: { systemId: "system.hvac", nodeId: "hvac.hrv.001", role: "ventilation" },
    dependencies: ["slab.basement"],
  });

  duct(
    reg,
    "hvac.duct.supply.riser",
    "Supply riser from air handler",
    [indoor[0], indoor[1] + 0.45, indoor[2]],
    plenum,
    0.22,
    ["hvac", "supply", "mechanical"],
    "Vertical supply from the air handler up to the under-joist trunk.",
    "Connect the plant to the floor system. Not a static-pressure calculation.",
    { role: "supply" },
  );
  duct(
    reg,
    "hvac.duct.supply.main",
    "Supply trunk",
    plenum,
    [indoor[0], underDuctY, 0.15],
    0.22,
    ["hvac", "supply"],
    "Main supply trunk hung below the joists.",
    "Carry supply air in the basement, not through the 2×10 joists. Schematic airflow, not CFD.",
    { role: "supply" },
  );
  duct(
    reg,
    "hvac.duct.supply.front",
    "Supply to front rooms",
    plenum,
    [indoor[0], underDuctY, 2.55],
    0.16,
    ["hvac", "supply"],
    "Supply branch along a joist bay toward the front rooms.",
    "Stay parallel to the joists until the terminal takeoff.",
    { role: "supply" },
  );
  duct(
    reg,
    "hvac.duct.supply.front.x",
    "Supply takeoff to front grille",
    [indoor[0], underDuctY, 2.55],
    [1.4, underDuctY, 2.55],
    0.14,
    ["hvac", "supply"],
    "Cross-joist takeoff hung below the joists.",
    "A hung duct may cross joists; it does not bore a 140 mm hole through them.",
    { role: "supply" },
  );
  duct(
    reg,
    "hvac.duct.supply.bath",
    "Supply to bathroom",
    plenum,
    [-3.1, underDuctY, indoor[2]],
    0.14,
    ["hvac", "supply", "bath"],
    "Supply branch hung below the joists toward the wet room.",
    "Run under the floor structure to the bathroom.",
    { role: "supply" },
  );
  duct(
    reg,
    "hvac.duct.supply.bath.z",
    "Supply bath turn",
    [-3.1, underDuctY, indoor[2]],
    [-3.1, underDuctY, -1.4],
    0.14,
    ["hvac", "supply", "bath"],
    "Bathroom takeoff along a joist bay.",
    "Axis-aligned under-floor run to the bath grille.",
    { role: "supply" },
  );
  duct(
    reg,
    "hvac.duct.supply.kitchen",
    "Supply to kitchen",
    [1.4, underDuctY, 2.55],
    [2.6, underDuctY, 2.55],
    0.14,
    ["hvac", "supply", "kitchen"],
    "Kitchen takeoff hung below the joists.",
    "A terminal run in the service zone, under the floor.",
    { role: "supply" },
  );
  duct(
    reg,
    "hvac.duct.supply.front.rise",
    "Front grille rise",
    [1.4, underDuctY, 2.55],
    [1.4, Y.floorTop + 0.02, 2.55],
    0.12,
    ["hvac", "supply"],
    "Rise through the floor at the front grille.",
    "The only above-floor supply is the terminal.",
    { role: "supply" },
  );
  duct(
    reg,
    "hvac.duct.supply.bath.rise",
    "Bath grille rise",
    [-3.1, underDuctY, -1.4],
    [-3.1, Y.floorTop + 0.02, -1.4],
    0.1,
    ["hvac", "supply", "bath"],
    "Rise through the floor at the bathroom grille.",
    "Terminal rise, not a trunk through the joists.",
    { role: "supply" },
  );
  duct(
    reg,
    "hvac.duct.supply.kitchen.rise",
    "Kitchen grille rise",
    [2.6, underDuctY, 2.55],
    [2.6, Y.floorTop + 0.02, 2.55],
    0.1,
    ["hvac", "supply", "kitchen"],
    "Rise through the floor at the kitchen grille.",
    "Terminal rise at the kitchen.",
    { role: "supply" },
  );

  addBox(reg, {
    id: "hvac.terminal.front.001",
    type: "terminal",
    label: "Front room supply grille",
    parentId: "assembly.hvac",
    trade: "hvac",
    center: [1.4, Y.floorTop + 0.02, 2.55],
    size: [0.35, 0.04, 0.18],
    material: MAT.steel,
    stage: 21,
    explodeGroup: "assembly.hvac",
    explodeVector: [0, 0.5, 0.8],
    tags: ["hvac", "supply"],
    short: "Supply outlet in the front living zone.",
    purpose: "Where supply air enters the room. Throw and CFM are not simulated.",
    visualization: "SCHEMATIC AIRFLOW",
    provenance: PROV_EDU,
    system: { systemId: "system.hvac", nodeId: "hvac.terminal.front.001", role: "supply-terminal" },
    dependencies: ["hvac.duct.supply.front.x"],
  });
  addBox(reg, {
    id: "hvac.terminal.bath.001",
    type: "terminal",
    label: "Bathroom supply grille",
    parentId: "assembly.hvac",
    trade: "hvac",
    center: [-3.1, Y.floorTop + 0.02, -1.4],
    size: [0.28, 0.04, 0.16],
    material: MAT.steel,
    stage: 21,
    explodeGroup: "assembly.wall.bath",
    explodeVector: [-0.4, 0.3, 0],
    tags: ["hvac", "supply", "bath"],
    short: "Supply outlet in the bathroom.",
    purpose: "A terminal on the bathroom supply branch.",
    visualization: "SCHEMATIC AIRFLOW",
    provenance: PROV_EDU,
    system: { systemId: "system.hvac", nodeId: "hvac.terminal.bath.001", role: "supply-terminal" },
    dependencies: ["hvac.duct.supply.bath.z"],
  });
  addBox(reg, {
    id: "hvac.terminal.kitchen.001",
    type: "terminal",
    label: "Kitchen supply grille",
    parentId: "assembly.hvac",
    trade: "hvac",
    center: [2.6, Y.floorTop + 0.02, 2.55],
    size: [0.3, 0.04, 0.16],
    material: MAT.steel,
    stage: 21,
    explodeGroup: "assembly.hvac",
    explodeVector: [0, 0.4, 0.9],
    tags: ["hvac", "supply", "kitchen"],
    short: "Supply outlet in the kitchen.",
    purpose: "A terminal on the kitchen supply branch.",
    visualization: "SCHEMATIC AIRFLOW",
    provenance: PROV_EDU,
    system: { systemId: "system.hvac", nodeId: "hvac.terminal.kitchen.001", role: "supply-terminal" },
    dependencies: ["hvac.duct.supply.kitchen.rise"],
  });

  duct(
    reg,
    "hvac.duct.return.main",
    "Return path",
    [0.1, underDuctY - 0.04, 0.15],
    [0.1, underDuctY - 0.04, indoor[2]],
    0.24,
    ["hvac", "return"],
    "Return trunk hung below the joists.",
    "Air coming back to be conditioned. Schematic, not a pressure model.",
    { role: "return" },
  );
  duct(
    reg,
    "hvac.duct.return.riser",
    "Return drop to air handler",
    [0.1, underDuctY - 0.04, indoor[2]],
    [indoor[0] - 0.25, indoor[1] + 0.35, indoor[2]],
    0.22,
    ["hvac", "return", "mechanical"],
    "Return drop from the under-joist trunk into the air handler.",
    "Close the air loop in the mechanical space.",
    { role: "return" },
  );
  duct(
    reg,
    "hvac.duct.return.rise",
    "Return grille drop",
    [0.1, Y.floorTop + 0.015, 0.15],
    [0.1, underDuctY - 0.04, 0.15],
    0.16,
    ["hvac", "return"],
    "Drop from the floor grille into the hung return.",
    "The grille is in the floor; the trunk is below the joists.",
    { role: "return" },
  );
  addBox(reg, {
    id: "hvac.terminal.return.001",
    type: "terminal",
    label: "Central return grille",
    parentId: "assembly.hvac",
    trade: "hvac",
    center: [0.1, Y.floorTop + 0.015, 0.15],
    size: [0.48, 0.03, 0.22],
    material: MAT.steel,
    stage: 21,
    explodeGroup: "assembly.hvac",
    explodeVector: [0, 0.4, 0],
    tags: ["hvac", "return"],
    short: "A simplified central return.",
    purpose: "Close the air loop conceptually.",
    visualization: "SCHEMATIC AIRFLOW",
    provenance: PROV_EDU,
    system: { systemId: "system.hvac", nodeId: "hvac.terminal.return.001", role: "return-terminal" },
    dependencies: ["hvac.duct.return.rise"],
  });

  addBox(reg, {
    id: "hvac.exhaust.bath.001",
    type: "exhaust",
    label: "Bathroom exhaust fan",
    parentId: "assembly.hvac",
    trade: "hvac",
    center: [-3.2, Y.wallTop - 0.08, -0.2],
    size: [0.22, 0.1, 0.22],
    material: MAT.steel,
    stage: 16,
    explodeGroup: "assembly.wall.bath",
    explodeVector: [0, 0.8, 0],
    localExplodeVector: [0, 0.35, 0],
    tags: ["hvac", "exhaust", "bath"],
    short: "Bathroom exhaust fan.",
    purpose: "Remove moisture-laden air. Rate and makeup air are not calculated.",
    visualization: "SCHEMATIC AIRFLOW",
    provenance: PROV_EDU,
    system: { systemId: "system.hvac", nodeId: "hvac.exhaust.bath.001", role: "exhaust" },
    dependencies: ["assembly.wall.bath"],
  });
  duct(
    reg,
    "hvac.exhaust.bath.duct",
    "Bath exhaust duct",
    [-3.2, Y.wallTop - 0.08, -0.2],
    [-halfL + 0.05, Y.wallTop - 0.08, -0.2],
    0.12,
    ["hvac", "exhaust", "bath"],
    "Exhaust duct to the left gable wall.",
    "A path from fan to outdoors. This is the topology the Break It challenge cuts.",
    {
      explodeGroup: "assembly.wall.bath",
      explodeVector: [-1.2, 0.5, 0],
      local: [-0.4, 0.2, 0],
      parentId: "assembly.wall.bath",
      role: "exhaust",
    },
  );
  addBox(reg, {
    id: "hvac.exhaust.bath.outlet",
    type: "exhaust",
    label: "Bath exhaust outlet",
    parentId: "assembly.hvac",
    trade: "hvac",
    center: [-halfL - 0.04, Y.wallTop - 0.08, -0.2],
    size: [0.08, 0.16, 0.16],
    material: MAT.steel,
    stage: 16,
    explodeGroup: "assembly.wall.left",
    explodeVector: [-2.0, 0.3, 0],
    tags: ["hvac", "exhaust"],
    short: "Exterior termination of the bathroom exhaust.",
    purpose: "Where exhaust air leaves the house.",
    visualization: "SCHEMATIC AIRFLOW",
    provenance: PROV_EDU,
    system: { systemId: "system.hvac", nodeId: "hvac.exhaust.bath.outlet", role: "exhaust-outlet" },
    dependencies: ["hvac.exhaust.bath.duct"],
  });

  addBox(reg, {
    id: "hvac.exhaust.kitchen.001",
    type: "exhaust",
    label: "Kitchen exhaust (concept)",
    parentId: "assembly.hvac",
    trade: "hvac",
    center: [2.75, Y.wallTop - 0.15, 3.05],
    size: [0.35, 0.12, 0.28],
    material: MAT.steel,
    stage: 16,
    explodeGroup: "assembly.wall.front",
    explodeVector: [0, 0.6, 1.6],
    tags: ["hvac", "exhaust", "kitchen"],
    short: "Kitchen range-hood concept.",
    purpose: "Point at cooking moisture and odour removal. Ducted vs recirculating is not a regulatory claim here.",
    visualization: "SCHEMATIC AIRFLOW",
    provenance: PROV_EDU,
    system: { systemId: "system.hvac", nodeId: "hvac.exhaust.kitchen.001", role: "exhaust" },
    dependencies: ["assembly.wall.front"],
  });

  addBox(reg, {
    id: "penetration.floor.hvac.front",
    type: "penetration",
    label: "Front supply floor penetration",
    parentId: "assembly.floor",
    trade: "hvac",
    center: [1.4, Y.floorTop, 2.55],
    size: [0.16, 0.05, 0.16],
    material: MAT.wood,
    stage: 16,
    explodeGroup: "assembly.floor",
    explodeVector: [0, 0.6, 0],
    tags: ["hvac", "penetration"],
    short: "Opening where the front supply rises through the subfloor.",
    purpose: "Host/trade penetration for the supply terminal.",
    penetration: { hostId: "subfloor.3", tradeComponentId: "hvac.duct.supply.front.rise", purpose: "supply-terminal" },
  });
  addBox(reg, {
    id: "penetration.floor.hvac.bath",
    type: "penetration",
    label: "Bath supply floor penetration",
    parentId: "assembly.floor",
    trade: "hvac",
    center: [-3.1, Y.floorTop, -1.4],
    size: [0.14, 0.05, 0.14],
    material: MAT.wood,
    stage: 16,
    explodeGroup: "assembly.floor",
    explodeVector: [0, 0.6, 0],
    tags: ["hvac", "penetration", "bath"],
    short: "Opening where the bathroom supply rises through the subfloor.",
    purpose: "Host/trade penetration for the bath terminal.",
    penetration: { hostId: "subfloor.0", tradeComponentId: "hvac.duct.supply.bath.rise", purpose: "supply-terminal" },
  });
  addBox(reg, {
    id: "penetration.floor.hvac.kitchen",
    type: "penetration",
    label: "Kitchen supply floor penetration",
    parentId: "assembly.floor",
    trade: "hvac",
    center: [2.6, Y.floorTop, 2.55],
    size: [0.14, 0.05, 0.14],
    material: MAT.wood,
    stage: 16,
    explodeGroup: "assembly.floor",
    explodeVector: [0, 0.6, 0],
    tags: ["hvac", "penetration", "kitchen"],
    short: "Opening where the kitchen supply rises through the subfloor.",
    purpose: "Host/trade penetration for the kitchen terminal.",
    penetration: { hostId: "subfloor.5", tradeComponentId: "hvac.duct.supply.kitchen.rise", purpose: "supply-terminal" },
  });
  addBox(reg, {
    id: "penetration.floor.hvac.return",
    type: "penetration",
    label: "Return floor penetration",
    parentId: "assembly.floor",
    trade: "hvac",
    center: [0.1, Y.floorTop, 0.15],
    size: [0.22, 0.05, 0.16],
    material: MAT.wood,
    stage: 16,
    explodeGroup: "assembly.floor",
    explodeVector: [0, 0.6, 0],
    tags: ["hvac", "penetration"],
    short: "Opening where the return drops through the subfloor.",
    purpose: "Host/trade penetration for the central return.",
    penetration: { hostId: "subfloor.3", tradeComponentId: "hvac.duct.return.rise", purpose: "return-terminal" },
  });
  addBox(reg, {
    id: "hvac.hanger.supply.001",
    type: "hanger",
    label: "Supply trunk hanger (representative)",
    parentId: "assembly.hvac",
    trade: "hvac",
    center: [indoor[0], underDuctY + 0.14, 0.85],
    size: [0.04, 0.12, 0.04],
    material: MAT.steel,
    stage: 16,
    explodeGroup: "assembly.hvac",
    explodeVector: [0, 0.4, 0],
    tags: ["hvac", "support"],
    short: "A representative strap hanging the supply trunk from the joists.",
    purpose: "Show that hung ducts need supports. Spacing is not a verified schedule.",
    provenance: { ...PROV_EDU, status: "not-evaluated", authority: "UNKNOWN" },
    dependencies: ["hvac.duct.supply.main"],
  });
}

export const HVAC_CONNECTIONS: SystemConnection[] = [
  { id: "hv.ref", from: "hvac.heatpump.indoor.001", to: "hvac.refrigerant.001", kind: "refrigerant" },
  { id: "hv.ref1b", from: "hvac.refrigerant.001", to: "hvac.refrigerant.002", kind: "refrigerant" },
  { id: "hv.ref2", from: "hvac.refrigerant.002", to: "hvac.refrigerant.003", kind: "refrigerant" },
  { id: "hv.ref3", from: "hvac.refrigerant.003", to: "hvac.refrigerant.004", kind: "refrigerant" },
  { id: "hv.ref4", from: "hvac.refrigerant.004", to: "hvac.heatpump.outdoor.001", kind: "refrigerant" },
  { id: "hv.cond", from: "hvac.heatpump.indoor.001", to: "hvac.condensate.001", kind: "condensate" },
  { id: "hv.sup0", from: "hvac.heatpump.indoor.001", to: "hvac.duct.supply.riser", kind: "air-supply" },
  { id: "hv.sup1", from: "hvac.duct.supply.riser", to: "hvac.duct.supply.main", kind: "air-supply" },
  { id: "hv.sup2", from: "hvac.duct.supply.main", to: "hvac.duct.supply.front", kind: "air-supply" },
  { id: "hv.sup2b", from: "hvac.duct.supply.front", to: "hvac.duct.supply.front.x", kind: "air-supply" },
  { id: "hv.sup3", from: "hvac.duct.supply.main", to: "hvac.duct.supply.bath", kind: "air-supply" },
  { id: "hv.sup3b", from: "hvac.duct.supply.bath", to: "hvac.duct.supply.bath.z", kind: "air-supply" },
  { id: "hv.sup4", from: "hvac.duct.supply.front.x", to: "hvac.duct.supply.kitchen", kind: "air-supply" },
  { id: "hv.t1", from: "hvac.duct.supply.front.x", to: "hvac.duct.supply.front.rise", kind: "air-supply" },
  { id: "hv.t1b", from: "hvac.duct.supply.front.rise", to: "hvac.terminal.front.001", kind: "air-supply" },
  { id: "hv.t2", from: "hvac.duct.supply.bath.z", to: "hvac.duct.supply.bath.rise", kind: "air-supply" },
  { id: "hv.t2b", from: "hvac.duct.supply.bath.rise", to: "hvac.terminal.bath.001", kind: "air-supply" },
  { id: "hv.t3", from: "hvac.duct.supply.kitchen", to: "hvac.duct.supply.kitchen.rise", kind: "air-supply" },
  { id: "hv.t3b", from: "hvac.duct.supply.kitchen.rise", to: "hvac.terminal.kitchen.001", kind: "air-supply" },
  { id: "hv.ret0", from: "hvac.terminal.return.001", to: "hvac.duct.return.rise", kind: "air-return" },
  { id: "hv.ret1", from: "hvac.duct.return.rise", to: "hvac.duct.return.main", kind: "air-return" },
  { id: "hv.ret1b", from: "hvac.duct.return.main", to: "hvac.duct.return.riser", kind: "air-return" },
  { id: "hv.ret2", from: "hvac.duct.return.riser", to: "hvac.heatpump.indoor.001", kind: "air-return" },
  { id: "hv.hrv", from: "hvac.hrv.001", to: "hvac.heatpump.indoor.001", kind: "air-supply" },
  { id: "hv.ex1", from: "hvac.exhaust.bath.001", to: "hvac.exhaust.bath.duct", kind: "exhaust" },
  { id: "hv.ex2", from: "hvac.exhaust.bath.duct", to: "hvac.exhaust.bath.outlet", kind: "exhaust" },
];
